[package]
name = "keepass-rs"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "keepass_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
keepass = { version = "0.13.19", features = ["save_kdbx4"] }
chrono = "0.4.45"
jni = "0.21.1"
prost = "0.13.5"
uuid = "1.23.3"
log = "0.4.33"
rust-argon2 = "3.0.0"

[build-dependencies]
prost-build = "0.13.5"
protoc-bin-vendored = "3.0.0"
