name: Bug Report
description: Template for bug report
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Overview
      description: Please describe exactly what the bug is and what you expected to happen instead.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce
      description: |
        Describe step by step, how to reproduce the bug. For example:
        1. Open the App
        2. Unlock the database
        3. App crashes
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: On which version of KeePassVault did this bug appear? Please write the exact version.
    validations:
      required: true
  - type: input
    id: androidversion
    attributes:
      label: Android Version
      description: What is your Android Version? (i.e. Android 13)
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device Model
      description: What device do you use (i.e. Pixel 6)
    validations:
      required: true
