name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-code-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt and validate decrypted data
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./.github/workflows/decrypt-and-validate-data.sh

      - name: Run spotless
        run: ./gradlew app:spotlessCheck

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt and validate decrypted data
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./.github/workflows/decrypt-and-validate-data.sh

      - name: Run tests
        run: ./gradlew app:test

  build-apks:
    name: Build and store apk files
    needs: [ check-code-style, run-tests ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - command: assembleGplayDebug
            fileName: app-gplay-debug.apk
            filePath: ./app/build/outputs/apk/gplay/debug/app-gplay-debug.apk

          - command: assembleGplayRelease
            fileName: app-gplay-release.apk
            filePath: ./app/build/outputs/apk/gplay/release/app-gplay-release.apk

          - command: assembleFdroidDebug
            fileName: app-fdroid-debug.apk
            filePath: ./app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk

          - command: assembleFdroidRelease
            fileName: app-fdroid-release.apk
            filePath: ./app/build/outputs/apk/fdroid/release/app-fdroid-release.apk

          - command: assembleFdroidAutomation
            fileName: app-fdroid-automation.apk
            filePath: ./app/build/outputs/apk/fdroid/automation/app-fdroid-automation.apk
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt and validate decrypted data
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./.github/workflows/decrypt-and-validate-data.sh

      - name: Build
        run: |
          ./gradlew app:${{ matrix.command }}

      - name: Store APK file
        uses: actions/upload-artifact@v4.6
        with:
          name: ${{ matrix.fileName }}
          path: ${{ matrix.filePath }}