name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-code-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt and validate decrypted data
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./.github/workflows/decrypt-and-validate-data.sh

      - name: Run spotless
        run: ./gradlew app:spotlessCheck

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt and validate decrypted data
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./.github/workflows/decrypt-and-validate-data.sh

      - name: Run tests
        run: ./gradlew app:test


  print-matrix-data:
    name: Print matrix data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - command: assembleGplayDebug
            filePath: ./app/build/outputs/apk/gplay/debug/app-gplay-debug.apk
    steps:
      - name: Print
        run: |
          echo "command=${{ matrix.command }}"
          echo "filePath=${{ matrix.filePath }}"

  build-apks:
    name: Build and store apk files
    needs: [ check-code-style, run-tests ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - command: assembleGplayDebug
            filePath: ./app/build/outputs/apk/gplay/debug/app-gplay-debug.apk
          - command: assembleGplayRelease
            filePath: ./app/build/outputs/apk/gplay/release/app-gplay-release.apk

          - command: assembleFdroidDebug
            filePath: ./app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
          - command: assembleFdroidRelease
            filePath: ./app/build/outputs/apk/fdroid/release/app-fdroid-release.apk
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt and validate decrypted data
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./.github/workflows/decrypt-and-validate-data.sh

      - name: Build
        run: |
          ./gradlew app:assemble${{ matrix.command }}

      - name: Store APK file
        uses: actions/upload-artifact@v3
        with:
          name: app-gplay-debug.apk
          path: |
            ${{ matrix.filePath }}