on:
  push:
    branches: master
    tags:
      - '*'

jobs:
  release_build:
    name: Create release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt and validate encrypted data
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          if [ -z "GPG_PASSPHRASE" ]; then
            ## Decrypt
            gpg --passphrase $GPG_PASSPHRASE --pinentry-mode loopback -o ./keys/debug.keystore -d ./keys/debug.keystore.gpg
            gpg --passphrase $GPG_PASSPHRASE --pinentry-mode loopback -o ./keys/release.keystore -d ./keys/release.keystore.gpg
            gpg --passphrase $GPG_PASSPHRASE --pinentry-mode loopback -o ./ci.properties -d ./ci.properties.gpg

            ## Validate
            echo "3a15a7065ed4a62a747af2e3477b0a3e1940a7bc2946df638b902bcb186998e7 *keys/debug.keystore" | sha256sum --check
            echo "36a3bb8b7bda141b414c2df7fac7dcd09a2775769c561e562d2b43f7b246bfa5 *keys/release.keystore" | sha256sum --check
            echo "b009011968e80d5b99eaa181141e6c94178a538c3dac0e413c43d5f95f50f557 *ci.properties" | sha256sum --check
          fi

      - name: Build debug and release apk's
        run: |
          ./gradlew app:assembleFdroidDebug app:assembleFdroidRelease

      - name: Store debug apk
        uses: actions/upload-artifact@v3
        with:
          name: app-fdroid-debug.apk
          path: |
            ./app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk

      - name: Store release apk
        uses: actions/upload-artifact@v3
        with:
          name: app-fdroid-release.apk
          path: |
            ./app/build/outputs/apk/fdroid/release/app-fdroid-release.apk

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            ./app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
            ./app/build/outputs/apk/fdroid/release/app-fdroid-release.apk
