name: Publish to Github and Google Play

on:
  push:
    branches: master
    tags:
      - '*.*.*'

jobs:
  publish-github-release:
    name: Publish Github release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt and validate decrypted data
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./.github/workflows/decrypt-and-validate-data.sh

      - name: Build apk's
        run: |
          ./gradlew app:assembleFdroidDebug app:assembleFdroidRelease app:assembleFdroidAutomation

      - name: Rename files
        run: |
          cp ./app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk ./keepassvault-debug.apk
          cp ./app/build/outputs/apk/fdroid/release/app-fdroid-release.apk ./keepassvault-release.apk
          cp ./app/build/outputs/apk/fdroid/automation/app-fdroid-automation.apk ./keepassvault-test.apk

      - name: Publish Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            ./keepassvault-debug.apk
            ./keepassvault-release.apk
            ./keepassvault-test.apk

  upload-to-google-play:
    name: Upload App Bundle to Google Play
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt and validate decrypted data
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./.github/workflows/decrypt-and-validate-data.sh

      - name: Upload to Google Play
        run: |
          ./gradlew publishGplayReleaseBundle