name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.1
        with:
          configurationFile: renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}